# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'konoiro-paint' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for konoiro-paint
	pod 'ACEDrawingView'

  target 'konoiro-paintTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'konoiro-paintUITests' do
    # Pods for testing
  end



end
